import type { User, Product, Service, Client, CompletedOrder } from "./types";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    username: "sarah",
    url: "https://coffee.local",
    email: "sarah@store.com",
    pin: "1234",
    password: "password123",
    role: "cashier",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Mike Chen",
    username: "mike",
    url: "https://coffee.local",
    email: "mike@store.com",
    pin: "2345",
    password: "password123",
    role: "cashier",
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "3",
    name: "Lisa Morrison",
    username: "lisa",
    url: "https://coffee.local",
    email: "lisa@store.com",
    pin: "3456",
    password: "password123",
    role: "manager",
    createdAt: new Date("2024-01-01"),
  },
];

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "Espresso",
    sku: "COFFEE-ESP",
    category: "All Products",
    price: 3.5,
    cost: 1.0,
    stock: 50,
    tax: 0.1,
    description: "Single shot espresso",
    createdAt: new Date(),
  },
  {
    id: "p2",
    name: "Cappuccino",
    sku: "COFFEE-CAP",
    category: "All Products",
    price: 4.5,
    cost: 1.5,
    stock: 40,
    tax: 0.1,
    description: "Espresso with steamed milk",
    createdAt: new Date(),
  },
  {
    id: "p3",
    name: "Latte",
    sku: "COFFEE-LAT",
    category: "All Products",
    price: 4.75,
    cost: 1.75,
    stock: 45,
    tax: 0.1,
    description: "Espresso with milk",
    createdAt: new Date(),
  },
  {
    id: "p4",
    name: "Croissant",
    sku: "PASTRY-CRO",
    category: "All Products",
    price: 3.99,
    cost: 1.2,
    stock: 30,
    tax: 0.1,
    description: "Butter croissant",
    createdAt: new Date(),
  },
  {
    id: "p5",
    name: "Blueberry Muffin",
    sku: "PASTRY-MUF",
    category: "All Products",
    price: 3.49,
    cost: 0.9,
    stock: 35,
    tax: 0.1,
    description: "Fresh blueberry muffin",
    createdAt: new Date(),
  },
  {
    id: "p6",
    name: "Sandwich",
    sku: "FOOD-SAN",
    category: "All Products",
    price: 8.99,
    cost: 3.0,
    stock: 20,
    tax: 0.1,
    description: "Turkey and avocado sandwich",
    createdAt: new Date(),
  },
  {
    id: "p7",
    name: "Orange Juice",
    sku: "BEVERAGE-OJ",
    category: "All Products",
    price: 3.99,
    cost: 1.0,
    stock: 25,
    tax: 0.1,
    description: "Fresh squeezed orange juice",
    createdAt: new Date(),
  },
  {
    id: "p8",
    name: "Americano",
    sku: "COFFEE-AME",
    category: "All Products",
    price: 3.25,
    cost: 0.9,
    stock: 60,
    tax: 0.1,
    description: "Espresso with hot water",
    createdAt: new Date(),
  },
];

export const mockServices: Service[] = [
  {
    id: "s1",
    name: "Delivery",
    price: 5.0,
    tax: 0.1,
    createdAt: new Date(),
  },
  {
    id: "s2",
    name: "Gift Wrapping",
    price: 2.0,
    tax: 0.1,
    createdAt: new Date(),
  },
];

export const mockClients: Client[] = [
  {
    id: "c1",
    name: "John Smith",
    email: "john@email.com",
    phone: "555-0101",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "c2",
    name: "Emma Wilson",
    email: "emma@email.com",
    phone: "555-0102",
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "c3",
    name: "David Brown",
    email: "david@email.com",
    phone: "555-0103",
    createdAt: new Date("2024-03-10"),
  },
];

export const mockCompletedOrders: CompletedOrder[] = [
  {
    id: "order-1",
    items: [
      {
        id: "item-1",
        productId: "p1",
        name: "Espresso",
        quantity: 2,
        price: 3.5,
        tax: 0.1,
        subtotal: 7.0,
      },
      {
        id: "item-2",
        productId: "p4",
        name: "Croissant",
        quantity: 1,
        price: 3.99,
        tax: 0.1,
        subtotal: 3.99,
      },
    ],
    client: mockClients[0],
    subtotal: 10.99,
    tax: 1.1,
    total: 12.09,
    discount: 0,
    discountType: "amount",
    payments: [{ method: "cash", amount: 12.09 }],
    change: 0,
    createdAt: new Date("2024-05-01"),
    updatedAt: new Date("2024-05-01"),
    completedAt: new Date("2024-05-01"),
    userId: "1",
  },
  {
    id: "order-2",
    items: [
      {
        id: "item-3",
        productId: "p2",
        name: "Cappuccino",
        quantity: 3,
        price: 4.5,
        tax: 0.1,
        subtotal: 13.5,
      },
    ],
    client: mockClients[1],
    subtotal: 13.5,
    tax: 1.35,
    total: 14.85,
    discount: 1.5,
    discountType: "amount",
    payments: [{ method: "card", amount: 14.85 }],
    change: 0,
    createdAt: new Date("2024-05-02"),
    updatedAt: new Date("2024-05-02"),
    completedAt: new Date("2024-05-02"),
    userId: "2",
  },
];

export const storeConfig = {
  name: "Coffee Corner",
  currency: "USD",
  currencySymbol: "$",
  taxRate: 0.1,
};
